name: Telegram Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Telegram Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          PRAYER_CITY: ${{ secrets.PRAYER_CITY }}
          PRAYER_COUNTRY: ${{ secrets.PRAYER_COUNTRY }}
        run: |
          python bot.py
